//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisiyefciDayi.ServiceReference2 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.FM_Web_ServiceSoap")]
    public interface FM_Web_ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStandings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetStandings(VisiyefciDayi.ServiceReference2.MatchType MatchType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMatchesList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMatchesList(VisiyefciDayi.ServiceReference2.MatchType MatchType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTopScorers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTopScorers(VisiyefciDayi.ServiceReference2.MatchType MatchType);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MatchType {
        
        /// <remarks/>
        AbantKupası,
        
        /// <remarks/>
        AbdullahKaptanKaymaklıCup,
        
        /// <remarks/>
        AfrikaUluslarKupası,
        
        /// <remarks/>
        AkdenizKupası,
        
        /// <remarks/>
        AkdenizKupası1,
        
        /// <remarks/>
        AkdenizKupası2,
        
        /// <remarks/>
        AlmanyaBundesliga,
        
        /// <remarks/>
        AnadoluCup,
        
        /// <remarks/>
        AnatolianCup,
        
        /// <remarks/>
        AntalyaCup,
        
        /// <remarks/>
        AntalyaKupası,
        
        /// <remarks/>
        ArjantinLigi,
        
        /// <remarks/>
        AspendosKupası,
        
        /// <remarks/>
        AvanosCupFutbolTurnuvası,
        
        /// <remarks/>
        AvrupaSüperKupası,
        
        /// <remarks/>
        AvrupaŞampiyonası,
        
        /// <remarks/>
        AvrupaŞampiyonasıElemeleri,
        
        /// <remarks/>
        BankAsya1Lig,
        
        /// <remarks/>
        BankAsya1LigeYükselmeMaçları,
        
        /// <remarks/>
        BarışKupası,
        
        /// <remarks/>
        BasriDirimliliCup,
        
        /// <remarks/>
        BelçikaLigi,
        
        /// <remarks/>
        BilyonerKupası,
        
        /// <remarks/>
        BoluFutbolTurnuvası,
        
        /// <remarks/>
        CopaAmerica,
        
        /// <remarks/>
        CornersporCup,
        
        /// <remarks/>
        ÇanakkaleZaferCup,
        
        /// <remarks/>
        DavrazCupFutbolTurnuvası,
        
        /// <remarks/>
        DoğanEmültayKupası,
        
        /// <remarks/>
        DostlukKupası,
        
        /// <remarks/>
        DünyaKupası,
        
        /// <remarks/>
        DünyaKupasıElemeleri,
        
        /// <remarks/>
        EfesKupası,
        
        /// <remarks/>
        EgeCup,
        
        /// <remarks/>
        EğirdirCupFutbolTurnuvası,
        
        /// <remarks/>
        FethiyeKupası,
        
        /// <remarks/>
        FIFAKonfederasyonKupası,
        
        /// <remarks/>
        FortisTürkiyeKupası,
        
        /// <remarks/>
        FransaLigue1,
        
        /// <remarks/>
        GeredeCupFutbolTurnuvası,
        
        /// <remarks/>
        GökmenYıldıranFutbolTurnuvası,
        
        /// <remarks/>
        GündüzTekinOnayKupası,
        
        /// <remarks/>
        HaliçCup,
        
        /// <remarks/>
        HasanDoğanKapadokyaFutbolTunuvası,
        
        /// <remarks/>
        HasanDoğanKızılcıhamamFutbolTurnuvası,
        
        /// <remarks/>
        HazırlıkMaçı,
        
        /// <remarks/>
        İngilterePremierLigi,
        
        /// <remarks/>
        İspanyaLaLiga,
        
        /// <remarks/>
        İsveçLigi,
        
        /// <remarks/>
        İsviçreLigi,
        
        /// <remarks/>
        İtalyaSerieA,
        
        /// <remarks/>
        İzmirKupası,
        
        /// <remarks/>
        İzmitCup,
        
        /// <remarks/>
        İzzetBaysalCup,
        
        /// <remarks/>
        KadriyeKupası,
        
        /// <remarks/>
        KapadokyaKupası,
        
        /// <remarks/>
        KardeşlikKupası,
        
        /// <remarks/>
        KartepeCup,
        
        /// <remarks/>
        KayaBelekKupası,
        
        /// <remarks/>
        KayaSideKupası,
        
        /// <remarks/>
        KızılcahamamKupası,
        
        /// <remarks/>
        LaraCup,
        
        /// <remarks/>
        MackolikComKupası,
        
        /// <remarks/>
        ManavgatCup,
        
        /// <remarks/>
        MetinOktayCup,
        
        /// <remarks/>
        MuratpaşaCup,
        
        /// <remarks/>
        NevşehirBelediyeBaşkanlığıCup,
        
        /// <remarks/>
        NevşehirKupası,
        
        /// <remarks/>
        ÖzelMaç,
        
        /// <remarks/>
        PatalyaKupası,
        
        /// <remarks/>
        SapancaCup,
        
        /// <remarks/>
        SerikCup,
        
        /// <remarks/>
        SevgiKupası,
        
        /// <remarks/>
        SporxComKupası,
        
        /// <remarks/>
        ŞampiyonlarLigi,
        
        /// <remarks/>
        TFF2Lig1Grup,
        
        /// <remarks/>
        TFF2Lig2Grup,
        
        /// <remarks/>
        TFF2Lig3Grup,
        
        /// <remarks/>
        TFF2Lig4Grup,
        
        /// <remarks/>
        TFF2Lig5Grup,
        
        /// <remarks/>
        TFF2LigYükselmeGrubu,
        
        /// <remarks/>
        TFF2LigeYükselmeMaçları,
        
        /// <remarks/>
        TFF3LigYükselmeGrubu,
        
        /// <remarks/>
        TorosCup,
        
        /// <remarks/>
        TurgutlusporBodrumFutbolTurnuvası,
        
        /// <remarks/>
        TurgutlusporGöremeKupasıFutbolTurnuvası,
        
        /// <remarks/>
        TurkcellSüperLig,
        
        /// <remarks/>
        TurkcellSüperLigeYükselmeMaçları,
        
        /// <remarks/>
        Türkiye2LigYükselmeGrubu,
        
        /// <remarks/>
        Türkiye2ligiYükselmeGrubu,
        
        /// <remarks/>
        Türkiye3Ligi1Grup,
        
        /// <remarks/>
        Türkiye3Ligi2Grup,
        
        /// <remarks/>
        Türkiye3Ligi3Grup,
        
        /// <remarks/>
        Türkiye3Ligi4Grup,
        
        /// <remarks/>
        Türkiye3Ligi5Grup,
        
        /// <remarks/>
        Türkiye3Ligi6Grup,
        
        /// <remarks/>
        Türkiye3Ligi7Grup,
        
        /// <remarks/>
        Türkiye3Ligi8Grup,
        
        /// <remarks/>
        TürkiyeBaşbakanlıkKupası,
        
        /// <remarks/>
        TürkiyeCumhurbaşkanlıkKupası,
        
        /// <remarks/>
        TürkiyeSporYazarlarıDerneğiKupası,
        
        /// <remarks/>
        TürkiyeSüperKupası,
        
        /// <remarks/>
        TürkiyeSüperLigi1959SezonuŞampiyonlukMaçları,
        
        /// <remarks/>
        TürkiyeSüperLigi19621963SezonuFinalGrubu,
        
        /// <remarks/>
        TürkiyeSüperLigiBeyazGrup,
        
        /// <remarks/>
        TürkiyeSüperLigiKırmızıGrup,
        
        /// <remarks/>
        UçhisarKupası,
        
        /// <remarks/>
        UEFAKupası,
        
        /// <remarks/>
        ÜrgüpKupası,
        
        /// <remarks/>
        YozgatFutbolTurnuvası,
        
        /// <remarks/>
        ZinnurSarıCup,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FM_Web_ServiceSoapChannel : VisiyefciDayi.ServiceReference2.FM_Web_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FM_Web_ServiceSoapClient : System.ServiceModel.ClientBase<VisiyefciDayi.ServiceReference2.FM_Web_ServiceSoap>, VisiyefciDayi.ServiceReference2.FM_Web_ServiceSoap {
        
        public FM_Web_ServiceSoapClient() {
        }
        
        public FM_Web_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FM_Web_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FM_Web_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FM_Web_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetStandings(VisiyefciDayi.ServiceReference2.MatchType MatchType) {
            return base.Channel.GetStandings(MatchType);
        }
        
        public System.Data.DataTable GetMatchesList(VisiyefciDayi.ServiceReference2.MatchType MatchType) {
            return base.Channel.GetMatchesList(MatchType);
        }
        
        public System.Data.DataTable GetTopScorers(VisiyefciDayi.ServiceReference2.MatchType MatchType) {
            return base.Channel.GetTopScorers(MatchType);
        }
    }
}
